# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smr.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tsmr.proto\x12\x05proto\"\x84\x01\n\x0cIndexRequest\x12\x15\n\rsymbolic_data\x18\x01 \x01(\x0c\x12.\n\x08\x65ncoding\x18\x02 \x01(\x0e\x32\x1c.proto.IndexRequest.Encoding\"-\n\x08\x45ncoding\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x42\x41SE64\x10\x01\x12\x08\n\x04UTF8\x10\x02\"9\n\x0f\x41\x64\x64PieceRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1a\n\x05notes\x18\x02 \x03(\x0b\x32\x0b.proto.Note\"\x1e\n\x10\x41\x64\x64PieceResponse\x12\n\n\x02id\x18\x01 \x01(\r\"\x12\n\x10\x41llPiecesRequest\"!\n\x11\x41llPiecesResponse\x12\x0c\n\x04pids\x18\x01 \x03(\r\"K\n\x04Note\x12\r\n\x05onset\x18\x01 \x01(\x02\x12\x0e\n\x06offset\x18\x02 \x01(\x02\x12\x11\n\tpitch_b40\x18\x03 \x01(\x05\x12\x11\n\tpiece_idx\x18\x06 \x01(\r\"#\n\x05Notes\x12\x1a\n\x05notes\x18\x01 \x03(\x0b\x32\x0b.proto.Note\">\n\x06Vector\x12\x1a\n\x05start\x18\x01 \x01(\x0b\x32\x0b.proto.Note\x12\x18\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x0b.proto.Note\"B\n\x07Measure\x12\x15\n\rsymbolic_data\x18\x01 \x01(\x0c\x12\x0e\n\x06number\x18\x02 \x01(\r\x12\x10\n\x08note_idx\x18\x03 \x01(\r\",\n\x08Measures\x12 \n\x08measures\x18\x01 \x03(\x0b\x32\x0e.proto.Measure\"\x19\n\nVectorsCsv\x12\x0b\n\x03\x63sv\x18\x01 \x01(\t\"(\n\nOccurrence\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\r\n\x05notes\x18\x02 \x03(\r\"5\n\x0bOccurrences\x12&\n\x0boccurrences\x18\x01 \x03(\x0b\x32\x11.proto.Occurrence2\xaa\x01\n\x05Index\x12/\n\nIndexNotes\x12\x13.proto.IndexRequest\x1a\x0c.proto.Notes\x12\x35\n\rIndexMeasures\x12\x13.proto.IndexRequest\x1a\x0f.proto.Measures\x12\x39\n\x0fIndexVectorsCsv\x12\x13.proto.IndexRequest\x1a\x11.proto.VectorsCsv2\xae\x01\n\x03Smr\x12*\n\x06Search\x12\x0c.proto.Notes\x1a\x12.proto.Occurrences\x12;\n\x08\x41\x64\x64Piece\x12\x16.proto.AddPieceRequest\x1a\x17.proto.AddPieceResponse\x12>\n\tAllPieces\x12\x17.proto.AllPiecesRequest\x1a\x18.proto.AllPiecesResponseb\x06proto3')
)



_INDEXREQUEST_ENCODING = _descriptor.EnumDescriptor(
  name='Encoding',
  full_name='proto.IndexRequest.Encoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE64', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UTF8', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=108,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_INDEXREQUEST_ENCODING)


_INDEXREQUEST = _descriptor.Descriptor(
  name='IndexRequest',
  full_name='proto.IndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbolic_data', full_name='proto.IndexRequest.symbolic_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='proto.IndexRequest.encoding', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _INDEXREQUEST_ENCODING,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=153,
)


_ADDPIECEREQUEST = _descriptor.Descriptor(
  name='AddPieceRequest',
  full_name='proto.AddPieceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.AddPieceRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.AddPieceRequest.notes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=212,
)


_ADDPIECERESPONSE = _descriptor.Descriptor(
  name='AddPieceResponse',
  full_name='proto.AddPieceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.AddPieceResponse.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=244,
)


_ALLPIECESREQUEST = _descriptor.Descriptor(
  name='AllPiecesRequest',
  full_name='proto.AllPiecesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=264,
)


_ALLPIECESRESPONSE = _descriptor.Descriptor(
  name='AllPiecesResponse',
  full_name='proto.AllPiecesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pids', full_name='proto.AllPiecesResponse.pids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=299,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='proto.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onset', full_name='proto.Note.onset', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='proto.Note.offset', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch_b40', full_name='proto.Note.pitch_b40', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='piece_idx', full_name='proto.Note.piece_idx', index=3,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=376,
)


_NOTES = _descriptor.Descriptor(
  name='Notes',
  full_name='proto.Notes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.Notes.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=413,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='proto.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='proto.Vector.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='proto.Vector.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=477,
)


_MEASURE = _descriptor.Descriptor(
  name='Measure',
  full_name='proto.Measure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbolic_data', full_name='proto.Measure.symbolic_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='proto.Measure.number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note_idx', full_name='proto.Measure.note_idx', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=545,
)


_MEASURES = _descriptor.Descriptor(
  name='Measures',
  full_name='proto.Measures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='measures', full_name='proto.Measures.measures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=591,
)


_VECTORSCSV = _descriptor.Descriptor(
  name='VectorsCsv',
  full_name='proto.VectorsCsv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='csv', full_name='proto.VectorsCsv.csv', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=618,
)


_OCCURRENCE = _descriptor.Descriptor(
  name='Occurrence',
  full_name='proto.Occurrence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='proto.Occurrence.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.Occurrence.notes', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=660,
)


_OCCURRENCES = _descriptor.Descriptor(
  name='Occurrences',
  full_name='proto.Occurrences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='occurrences', full_name='proto.Occurrences.occurrences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=715,
)

_INDEXREQUEST.fields_by_name['encoding'].enum_type = _INDEXREQUEST_ENCODING
_INDEXREQUEST_ENCODING.containing_type = _INDEXREQUEST
_ADDPIECEREQUEST.fields_by_name['notes'].message_type = _NOTE
_NOTES.fields_by_name['notes'].message_type = _NOTE
_VECTOR.fields_by_name['start'].message_type = _NOTE
_VECTOR.fields_by_name['end'].message_type = _NOTE
_MEASURES.fields_by_name['measures'].message_type = _MEASURE
_OCCURRENCES.fields_by_name['occurrences'].message_type = _OCCURRENCE
DESCRIPTOR.message_types_by_name['IndexRequest'] = _INDEXREQUEST
DESCRIPTOR.message_types_by_name['AddPieceRequest'] = _ADDPIECEREQUEST
DESCRIPTOR.message_types_by_name['AddPieceResponse'] = _ADDPIECERESPONSE
DESCRIPTOR.message_types_by_name['AllPiecesRequest'] = _ALLPIECESREQUEST
DESCRIPTOR.message_types_by_name['AllPiecesResponse'] = _ALLPIECESRESPONSE
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['Notes'] = _NOTES
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['Measure'] = _MEASURE
DESCRIPTOR.message_types_by_name['Measures'] = _MEASURES
DESCRIPTOR.message_types_by_name['VectorsCsv'] = _VECTORSCSV
DESCRIPTOR.message_types_by_name['Occurrence'] = _OCCURRENCE
DESCRIPTOR.message_types_by_name['Occurrences'] = _OCCURRENCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IndexRequest = _reflection.GeneratedProtocolMessageType('IndexRequest', (_message.Message,), dict(
  DESCRIPTOR = _INDEXREQUEST,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.IndexRequest)
  ))
_sym_db.RegisterMessage(IndexRequest)

AddPieceRequest = _reflection.GeneratedProtocolMessageType('AddPieceRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDPIECEREQUEST,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddPieceRequest)
  ))
_sym_db.RegisterMessage(AddPieceRequest)

AddPieceResponse = _reflection.GeneratedProtocolMessageType('AddPieceResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDPIECERESPONSE,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddPieceResponse)
  ))
_sym_db.RegisterMessage(AddPieceResponse)

AllPiecesRequest = _reflection.GeneratedProtocolMessageType('AllPiecesRequest', (_message.Message,), dict(
  DESCRIPTOR = _ALLPIECESREQUEST,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AllPiecesRequest)
  ))
_sym_db.RegisterMessage(AllPiecesRequest)

AllPiecesResponse = _reflection.GeneratedProtocolMessageType('AllPiecesResponse', (_message.Message,), dict(
  DESCRIPTOR = _ALLPIECESRESPONSE,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AllPiecesResponse)
  ))
_sym_db.RegisterMessage(AllPiecesResponse)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
  DESCRIPTOR = _NOTE,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Note)
  ))
_sym_db.RegisterMessage(Note)

Notes = _reflection.GeneratedProtocolMessageType('Notes', (_message.Message,), dict(
  DESCRIPTOR = _NOTES,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Notes)
  ))
_sym_db.RegisterMessage(Notes)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Vector)
  ))
_sym_db.RegisterMessage(Vector)

Measure = _reflection.GeneratedProtocolMessageType('Measure', (_message.Message,), dict(
  DESCRIPTOR = _MEASURE,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Measure)
  ))
_sym_db.RegisterMessage(Measure)

Measures = _reflection.GeneratedProtocolMessageType('Measures', (_message.Message,), dict(
  DESCRIPTOR = _MEASURES,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Measures)
  ))
_sym_db.RegisterMessage(Measures)

VectorsCsv = _reflection.GeneratedProtocolMessageType('VectorsCsv', (_message.Message,), dict(
  DESCRIPTOR = _VECTORSCSV,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.VectorsCsv)
  ))
_sym_db.RegisterMessage(VectorsCsv)

Occurrence = _reflection.GeneratedProtocolMessageType('Occurrence', (_message.Message,), dict(
  DESCRIPTOR = _OCCURRENCE,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Occurrence)
  ))
_sym_db.RegisterMessage(Occurrence)

Occurrences = _reflection.GeneratedProtocolMessageType('Occurrences', (_message.Message,), dict(
  DESCRIPTOR = _OCCURRENCES,
  __module__ = 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Occurrences)
  ))
_sym_db.RegisterMessage(Occurrences)



_INDEX = _descriptor.ServiceDescriptor(
  name='Index',
  full_name='proto.Index',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=718,
  serialized_end=888,
  methods=[
  _descriptor.MethodDescriptor(
    name='IndexNotes',
    full_name='proto.Index.IndexNotes',
    index=0,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_NOTES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IndexMeasures',
    full_name='proto.Index.IndexMeasures',
    index=1,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_MEASURES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IndexVectorsCsv',
    full_name='proto.Index.IndexVectorsCsv',
    index=2,
    containing_service=None,
    input_type=_INDEXREQUEST,
    output_type=_VECTORSCSV,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INDEX)

DESCRIPTOR.services_by_name['Index'] = _INDEX


_SMR = _descriptor.ServiceDescriptor(
  name='Smr',
  full_name='proto.Smr',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=891,
  serialized_end=1065,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='proto.Smr.Search',
    index=0,
    containing_service=None,
    input_type=_NOTES,
    output_type=_OCCURRENCES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPiece',
    full_name='proto.Smr.AddPiece',
    index=1,
    containing_service=None,
    input_type=_ADDPIECEREQUEST,
    output_type=_ADDPIECERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AllPieces',
    full_name='proto.Smr.AllPieces',
    index=2,
    containing_service=None,
    input_type=_ALLPIECESREQUEST,
    output_type=_ALLPIECESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMR)

DESCRIPTOR.services_by_name['Smr'] = _SMR

# @@protoc_insertion_point(module_scope)
