# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smr.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tsmr.proto\x12\x05proto\":\n\x0f\x41\x64\x64PieceRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x1a\n\x05notes\x18\x02 \x03(\x0b\x32\x0b.proto.Note\"\x12\n\x10\x41\x64\x64PieceResponse\"\x14\n\x12GetPieceIdsRequest\"#\n\x13GetPieceIdsResponse\x12\x0c\n\x04pids\x18\x01 \x03(\r\"9\n\rSearchRequest\x12\x1a\n\x05notes\x18\x01 \x03(\x0b\x32\x0b.proto.Note\x12\x0c\n\x04pids\x18\x02 \x03(\r\"8\n\x0eSearchResponse\x12&\n\x0boccurrences\x18\x01 \x03(\x0b\x32\x11.proto.Occurrence\"G\n\x04Note\x12\r\n\x05onset\x18\x01 \x01(\x02\x12\x0e\n\x06offset\x18\x02 \x01(\x02\x12\r\n\x05pitch\x18\x03 \x01(\x05\x12\x11\n\tpiece_idx\x18\x04 \x01(\r\"5\n\nOccurrence\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x1a\n\x05notes\x18\x02 \x03(\x0b\x32\x0b.proto.Note2\xbf\x01\n\x03Smr\x12\x35\n\x06Search\x12\x14.proto.SearchRequest\x1a\x15.proto.SearchResponse\x12;\n\x08\x41\x64\x64Piece\x12\x16.proto.AddPieceRequest\x1a\x17.proto.AddPieceResponse\x12\x44\n\x0bGetPieceIds\x12\x19.proto.GetPieceIdsRequest\x1a\x1a.proto.GetPieceIdsResponseb\x06proto3')
)




_ADDPIECEREQUEST = _descriptor.Descriptor(
  name='AddPieceRequest',
  full_name='proto.AddPieceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='proto.AddPieceRequest.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.AddPieceRequest.notes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=78,
)


_ADDPIECERESPONSE = _descriptor.Descriptor(
  name='AddPieceResponse',
  full_name='proto.AddPieceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=98,
)


_GETPIECEIDSREQUEST = _descriptor.Descriptor(
  name='GetPieceIdsRequest',
  full_name='proto.GetPieceIdsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=120,
)


_GETPIECEIDSRESPONSE = _descriptor.Descriptor(
  name='GetPieceIdsResponse',
  full_name='proto.GetPieceIdsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pids', full_name='proto.GetPieceIdsResponse.pids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=157,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='proto.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.SearchRequest.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pids', full_name='proto.SearchRequest.pids', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=216,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='proto.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='occurrences', full_name='proto.SearchResponse.occurrences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=274,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='proto.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onset', full_name='proto.Note.onset', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='proto.Note.offset', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='proto.Note.pitch', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='piece_idx', full_name='proto.Note.piece_idx', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=347,
)


_OCCURRENCE = _descriptor.Descriptor(
  name='Occurrence',
  full_name='proto.Occurrence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='proto.Occurrence.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notes', full_name='proto.Occurrence.notes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=402,
)

_ADDPIECEREQUEST.fields_by_name['notes'].message_type = _NOTE
_SEARCHREQUEST.fields_by_name['notes'].message_type = _NOTE
_SEARCHRESPONSE.fields_by_name['occurrences'].message_type = _OCCURRENCE
_OCCURRENCE.fields_by_name['notes'].message_type = _NOTE
DESCRIPTOR.message_types_by_name['AddPieceRequest'] = _ADDPIECEREQUEST
DESCRIPTOR.message_types_by_name['AddPieceResponse'] = _ADDPIECERESPONSE
DESCRIPTOR.message_types_by_name['GetPieceIdsRequest'] = _GETPIECEIDSREQUEST
DESCRIPTOR.message_types_by_name['GetPieceIdsResponse'] = _GETPIECEIDSRESPONSE
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
DESCRIPTOR.message_types_by_name['Occurrence'] = _OCCURRENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddPieceRequest = _reflection.GeneratedProtocolMessageType('AddPieceRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDPIECEREQUEST,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddPieceRequest)
  })
_sym_db.RegisterMessage(AddPieceRequest)

AddPieceResponse = _reflection.GeneratedProtocolMessageType('AddPieceResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDPIECERESPONSE,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddPieceResponse)
  })
_sym_db.RegisterMessage(AddPieceResponse)

GetPieceIdsRequest = _reflection.GeneratedProtocolMessageType('GetPieceIdsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPIECEIDSREQUEST,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetPieceIdsRequest)
  })
_sym_db.RegisterMessage(GetPieceIdsRequest)

GetPieceIdsResponse = _reflection.GeneratedProtocolMessageType('GetPieceIdsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPIECEIDSRESPONSE,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetPieceIdsResponse)
  })
_sym_db.RegisterMessage(GetPieceIdsResponse)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
  'DESCRIPTOR' : _NOTE,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Note)
  })
_sym_db.RegisterMessage(Note)

Occurrence = _reflection.GeneratedProtocolMessageType('Occurrence', (_message.Message,), {
  'DESCRIPTOR' : _OCCURRENCE,
  '__module__' : 'smr_pb2'
  # @@protoc_insertion_point(class_scope:proto.Occurrence)
  })
_sym_db.RegisterMessage(Occurrence)



_SMR = _descriptor.ServiceDescriptor(
  name='Smr',
  full_name='proto.Smr',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=405,
  serialized_end=596,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='proto.Smr.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPiece',
    full_name='proto.Smr.AddPiece',
    index=1,
    containing_service=None,
    input_type=_ADDPIECEREQUEST,
    output_type=_ADDPIECERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPieceIds',
    full_name='proto.Smr.GetPieceIds',
    index=2,
    containing_service=None,
    input_type=_GETPIECEIDSREQUEST,
    output_type=_GETPIECEIDSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMR)

DESCRIPTOR.services_by_name['Smr'] = _SMR

# @@protoc_insertion_point(module_scope)
